<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="dFD" nsURI="http://www.example.org/dFD" nsPrefix="dFD">
  <eClassifiers xsi:type="ecore:EClass" name="Almacen" eSuperTypes="#//Elemento"/>
  <eClassifiers xsi:type="ecore:EClass" name="Flujo">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nombre" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="anterior" eType="#//Elemento"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="siguiente" eType="#//Elemento"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Proceso" eSuperTypes="#//Elemento"/>
  <eClassifiers xsi:type="ecore:EClass" name="EntidadExterna" eSuperTypes="#//Elemento"/>
  <eClassifiers xsi:type="ecore:EClass" name="DFD">
    <eStructuralFeatures xsi:type="ecore:EReference" name="flujo" upperBound="-1"
        eType="#//Flujo" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="elemento" upperBound="-1"
        eType="#//Elemento" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Elemento" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nombre" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
