<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="DFD" nsURI="http://www.example.org/DFD" nsPrefix="DFD">
  <eClassifiers xsi:type="ecore:EClass" name="Cliente">
    <eStructuralFeatures xsi:type="ecore:EReference" name="pedido" upperBound="-1"
        eType="#//Pedido" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nombre" ordered="false"
        unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"
        changeable="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" ordered="false" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Int"
        changeable="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Pedido">
    <eStructuralFeatures xsi:type="ecore:EReference" name="articulo" upperBound="-1"
        eType="#//Articulo" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" ordered="false" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Int"
        changeable="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="descripcion" ordered="false"
        unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"
        changeable="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="estado" upperBound="3"
        eType="#//Estado"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Articulo">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" ordered="false" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Int"
        changeable="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="descripcion" ordered="false"
        unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"
        changeable="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="proveedor" eType="#//Proveedor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Proveedor">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" ordered="false" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Int"
        changeable="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nombre" ordered="false"
        unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"
        changeable="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Estado"/>
  <eClassifiers xsi:type="ecore:EClass" name="Transicion">
    <eStructuralFeatures xsi:type="ecore:EReference" name="anterior" eType="#//Estado"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="siguirnte" eType="#//Estado"/>
  </eClassifiers>
</ecore:EPackage>
