/*
 * generated by Xtext 2.23.0
 */
package co.edu.javeriana.dfd;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class DFDRuntimeModule extends AbstractDFDRuntimeModule {
}
