/*
 * generated by Xtext 2.23.0
 */
package co.edu.javeriana.dfd;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class DFDStandaloneSetup extends DFDStandaloneSetupGenerated {

	public static void doSetup() {
		new DFDStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
