/**
 * generated by Xtext 2.23.0
 */
package co.edu.javeriana.dfd.dFD.impl;

import co.edu.javeriana.dfd.dFD.Almacen;
import co.edu.javeriana.dfd.dFD.DFDPackage;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Almacen</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class AlmacenImpl extends ElementoImpl implements Almacen
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected AlmacenImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return DFDPackage.Literals.ALMACEN;
  }

} //AlmacenImpl
