/**
 * generated by Xtext 2.23.0
 */
package co.edu.javeriana.dfd.dFD.impl;

import co.edu.javeriana.dfd.dFD.DFDPackage;
import co.edu.javeriana.dfd.dFD.EntidadExterna;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Entidad Externa</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class EntidadExternaImpl extends ElementoImpl implements EntidadExterna
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected EntidadExternaImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return DFDPackage.Literals.ENTIDAD_EXTERNA;
  }

} //EntidadExternaImpl
