/**
 * generated by Xtext 2.23.0
 */
package co.edu.javeriana.dfd.dFD.impl;

import co.edu.javeriana.dfd.dFD.DFDPackage;
import co.edu.javeriana.dfd.dFD.EString;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>EString</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class EStringImpl extends MinimalEObjectImpl.Container implements EString
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected EStringImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return DFDPackage.Literals.ESTRING;
  }

} //EStringImpl
