/**
 * generated by Xtext 2.23.0
 */
package co.edu.javeriana.dfd.dFD.impl;

import co.edu.javeriana.dfd.dFD.DFDPackage;
import co.edu.javeriana.dfd.dFD.EString;
import co.edu.javeriana.dfd.dFD.Flujo;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Flujo</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link co.edu.javeriana.dfd.dFD.impl.FlujoImpl#getName <em>Name</em>}</li>
 *   <li>{@link co.edu.javeriana.dfd.dFD.impl.FlujoImpl#getAnterior <em>Anterior</em>}</li>
 *   <li>{@link co.edu.javeriana.dfd.dFD.impl.FlujoImpl#getNombre <em>Nombre</em>}</li>
 *   <li>{@link co.edu.javeriana.dfd.dFD.impl.FlujoImpl#getSiguiente <em>Siguiente</em>}</li>
 * </ul>
 *
 * @generated
 */
public class FlujoImpl extends MinimalEObjectImpl.Container implements Flujo
{
  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected EString name;

  /**
   * The cached value of the '{@link #getAnterior() <em>Anterior</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAnterior()
   * @generated
   * @ordered
   */
  protected EString anterior;

  /**
   * The cached value of the '{@link #getNombre() <em>Nombre</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getNombre()
   * @generated
   * @ordered
   */
  protected EString nombre;

  /**
   * The cached value of the '{@link #getSiguiente() <em>Siguiente</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSiguiente()
   * @generated
   * @ordered
   */
  protected EString siguiente;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected FlujoImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return DFDPackage.Literals.FLUJO;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EString getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetName(EString newName, NotificationChain msgs)
  {
    EString oldName = name;
    name = newName;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, DFDPackage.FLUJO__NAME, oldName, newName);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setName(EString newName)
  {
    if (newName != name)
    {
      NotificationChain msgs = null;
      if (name != null)
        msgs = ((InternalEObject)name).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - DFDPackage.FLUJO__NAME, null, msgs);
      if (newName != null)
        msgs = ((InternalEObject)newName).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - DFDPackage.FLUJO__NAME, null, msgs);
      msgs = basicSetName(newName, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, DFDPackage.FLUJO__NAME, newName, newName));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EString getAnterior()
  {
    return anterior;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetAnterior(EString newAnterior, NotificationChain msgs)
  {
    EString oldAnterior = anterior;
    anterior = newAnterior;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, DFDPackage.FLUJO__ANTERIOR, oldAnterior, newAnterior);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setAnterior(EString newAnterior)
  {
    if (newAnterior != anterior)
    {
      NotificationChain msgs = null;
      if (anterior != null)
        msgs = ((InternalEObject)anterior).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - DFDPackage.FLUJO__ANTERIOR, null, msgs);
      if (newAnterior != null)
        msgs = ((InternalEObject)newAnterior).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - DFDPackage.FLUJO__ANTERIOR, null, msgs);
      msgs = basicSetAnterior(newAnterior, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, DFDPackage.FLUJO__ANTERIOR, newAnterior, newAnterior));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EString getNombre()
  {
    return nombre;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetNombre(EString newNombre, NotificationChain msgs)
  {
    EString oldNombre = nombre;
    nombre = newNombre;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, DFDPackage.FLUJO__NOMBRE, oldNombre, newNombre);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setNombre(EString newNombre)
  {
    if (newNombre != nombre)
    {
      NotificationChain msgs = null;
      if (nombre != null)
        msgs = ((InternalEObject)nombre).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - DFDPackage.FLUJO__NOMBRE, null, msgs);
      if (newNombre != null)
        msgs = ((InternalEObject)newNombre).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - DFDPackage.FLUJO__NOMBRE, null, msgs);
      msgs = basicSetNombre(newNombre, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, DFDPackage.FLUJO__NOMBRE, newNombre, newNombre));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EString getSiguiente()
  {
    return siguiente;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetSiguiente(EString newSiguiente, NotificationChain msgs)
  {
    EString oldSiguiente = siguiente;
    siguiente = newSiguiente;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, DFDPackage.FLUJO__SIGUIENTE, oldSiguiente, newSiguiente);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setSiguiente(EString newSiguiente)
  {
    if (newSiguiente != siguiente)
    {
      NotificationChain msgs = null;
      if (siguiente != null)
        msgs = ((InternalEObject)siguiente).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - DFDPackage.FLUJO__SIGUIENTE, null, msgs);
      if (newSiguiente != null)
        msgs = ((InternalEObject)newSiguiente).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - DFDPackage.FLUJO__SIGUIENTE, null, msgs);
      msgs = basicSetSiguiente(newSiguiente, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, DFDPackage.FLUJO__SIGUIENTE, newSiguiente, newSiguiente));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case DFDPackage.FLUJO__NAME:
        return basicSetName(null, msgs);
      case DFDPackage.FLUJO__ANTERIOR:
        return basicSetAnterior(null, msgs);
      case DFDPackage.FLUJO__NOMBRE:
        return basicSetNombre(null, msgs);
      case DFDPackage.FLUJO__SIGUIENTE:
        return basicSetSiguiente(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case DFDPackage.FLUJO__NAME:
        return getName();
      case DFDPackage.FLUJO__ANTERIOR:
        return getAnterior();
      case DFDPackage.FLUJO__NOMBRE:
        return getNombre();
      case DFDPackage.FLUJO__SIGUIENTE:
        return getSiguiente();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case DFDPackage.FLUJO__NAME:
        setName((EString)newValue);
        return;
      case DFDPackage.FLUJO__ANTERIOR:
        setAnterior((EString)newValue);
        return;
      case DFDPackage.FLUJO__NOMBRE:
        setNombre((EString)newValue);
        return;
      case DFDPackage.FLUJO__SIGUIENTE:
        setSiguiente((EString)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case DFDPackage.FLUJO__NAME:
        setName((EString)null);
        return;
      case DFDPackage.FLUJO__ANTERIOR:
        setAnterior((EString)null);
        return;
      case DFDPackage.FLUJO__NOMBRE:
        setNombre((EString)null);
        return;
      case DFDPackage.FLUJO__SIGUIENTE:
        setSiguiente((EString)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case DFDPackage.FLUJO__NAME:
        return name != null;
      case DFDPackage.FLUJO__ANTERIOR:
        return anterior != null;
      case DFDPackage.FLUJO__NOMBRE:
        return nombre != null;
      case DFDPackage.FLUJO__SIGUIENTE:
        return siguiente != null;
    }
    return super.eIsSet(featureID);
  }

} //FlujoImpl
