/**
 * generated by Xtext 2.23.0
 */
package co.edu.javeriana.dfd.dFD.impl;

import co.edu.javeriana.dfd.dFD.DFDPackage;
import co.edu.javeriana.dfd.dFD.Proceso;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Proceso</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class ProcesoImpl extends ElementoImpl implements Proceso
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ProcesoImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return DFDPackage.Literals.PROCESO;
  }

} //ProcesoImpl
