/*
 * generated by Xtext 2.23.0
 */
package co.edu.javeriana.dfd.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractDFDScopeProvider extends DelegatingScopeProvider {
}
