/*
 * generated by Xtext 2.23.0
 */
package co.edu.javeriana.dfd.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class DFDUiModule extends AbstractDFDUiModule {

	public DFDUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
