/*
 * generated by Xtext 2.23.0
 */
package co.edu.javeriana.dfd.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class DFDGrammarAccess extends AbstractElementFinder.AbstractGrammarElementFinder {
	
	public class DFDElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "co.edu.javeriana.dfd.DFD.DFD");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cDFDAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cDFDKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cFlujoKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3_1 = (Keyword)cGroup_3.eContents().get(1);
		private final Assignment cFlujoAssignment_3_2 = (Assignment)cGroup_3.eContents().get(2);
		private final RuleCall cFlujoFlujoParserRuleCall_3_2_0 = (RuleCall)cFlujoAssignment_3_2.eContents().get(0);
		private final Group cGroup_3_3 = (Group)cGroup_3.eContents().get(3);
		private final Keyword cCommaKeyword_3_3_0 = (Keyword)cGroup_3_3.eContents().get(0);
		private final Assignment cFlujoAssignment_3_3_1 = (Assignment)cGroup_3_3.eContents().get(1);
		private final RuleCall cFlujoFlujoParserRuleCall_3_3_1_0 = (RuleCall)cFlujoAssignment_3_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_3_4 = (Keyword)cGroup_3.eContents().get(4);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cElementoKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_4_1 = (Keyword)cGroup_4.eContents().get(1);
		private final Assignment cElementoAssignment_4_2 = (Assignment)cGroup_4.eContents().get(2);
		private final RuleCall cElementoElementoParserRuleCall_4_2_0 = (RuleCall)cElementoAssignment_4_2.eContents().get(0);
		private final Group cGroup_4_3 = (Group)cGroup_4.eContents().get(3);
		private final Keyword cCommaKeyword_4_3_0 = (Keyword)cGroup_4_3.eContents().get(0);
		private final Assignment cElementoAssignment_4_3_1 = (Assignment)cGroup_4_3.eContents().get(1);
		private final RuleCall cElementoElementoParserRuleCall_4_3_1_0 = (RuleCall)cElementoAssignment_4_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4_4 = (Keyword)cGroup_4.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//DFD:
		//	{DFD}
		//	'DFD'
		//	'{' ('flujo' '{' flujo+=Flujo ("," flujo+=Flujo)* '}')? ('elemento' '{' elemento+=Elemento ("," elemento+=Elemento)*
		//	'}')?
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//{DFD} 'DFD' '{' ('flujo' '{' flujo+=Flujo ("," flujo+=Flujo)* '}')? ('elemento' '{' elemento+=Elemento (","
		//elemento+=Elemento)* '}')? '}'
		public Group getGroup() { return cGroup; }
		
		//{DFD}
		public Action getDFDAction_0() { return cDFDAction_0; }
		
		//'DFD'
		public Keyword getDFDKeyword_1() { return cDFDKeyword_1; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//('flujo' '{' flujo+=Flujo ("," flujo+=Flujo)* '}')?
		public Group getGroup_3() { return cGroup_3; }
		
		//'flujo'
		public Keyword getFlujoKeyword_3_0() { return cFlujoKeyword_3_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3_1() { return cLeftCurlyBracketKeyword_3_1; }
		
		//flujo+=Flujo
		public Assignment getFlujoAssignment_3_2() { return cFlujoAssignment_3_2; }
		
		//Flujo
		public RuleCall getFlujoFlujoParserRuleCall_3_2_0() { return cFlujoFlujoParserRuleCall_3_2_0; }
		
		//("," flujo+=Flujo)*
		public Group getGroup_3_3() { return cGroup_3_3; }
		
		//","
		public Keyword getCommaKeyword_3_3_0() { return cCommaKeyword_3_3_0; }
		
		//flujo+=Flujo
		public Assignment getFlujoAssignment_3_3_1() { return cFlujoAssignment_3_3_1; }
		
		//Flujo
		public RuleCall getFlujoFlujoParserRuleCall_3_3_1_0() { return cFlujoFlujoParserRuleCall_3_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_3_4() { return cRightCurlyBracketKeyword_3_4; }
		
		//('elemento' '{' elemento+=Elemento ("," elemento+=Elemento)* '}')?
		public Group getGroup_4() { return cGroup_4; }
		
		//'elemento'
		public Keyword getElementoKeyword_4_0() { return cElementoKeyword_4_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_4_1() { return cLeftCurlyBracketKeyword_4_1; }
		
		//elemento+=Elemento
		public Assignment getElementoAssignment_4_2() { return cElementoAssignment_4_2; }
		
		//Elemento
		public RuleCall getElementoElementoParserRuleCall_4_2_0() { return cElementoElementoParserRuleCall_4_2_0; }
		
		//("," elemento+=Elemento)*
		public Group getGroup_4_3() { return cGroup_4_3; }
		
		//","
		public Keyword getCommaKeyword_4_3_0() { return cCommaKeyword_4_3_0; }
		
		//elemento+=Elemento
		public Assignment getElementoAssignment_4_3_1() { return cElementoAssignment_4_3_1; }
		
		//Elemento
		public RuleCall getElementoElementoParserRuleCall_4_3_1_0() { return cElementoElementoParserRuleCall_4_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4_4() { return cRightCurlyBracketKeyword_4_4; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}
	public class ElementoElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "co.edu.javeriana.dfd.DFD.Elemento");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cProcesoParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cEntidadExternaParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cAlmacenParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		
		//Elemento:
		//	Proceso | EntidadExterna | Almacen;
		@Override public ParserRule getRule() { return rule; }
		
		//Proceso | EntidadExterna | Almacen
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//Proceso
		public RuleCall getProcesoParserRuleCall_0() { return cProcesoParserRuleCall_0; }
		
		//EntidadExterna
		public RuleCall getEntidadExternaParserRuleCall_1() { return cEntidadExternaParserRuleCall_1; }
		
		//Almacen
		public RuleCall getAlmacenParserRuleCall_2() { return cAlmacenParserRuleCall_2; }
	}
	public class FlujoElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "co.edu.javeriana.dfd.DFD.Flujo");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cFlujoAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cFlujoKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Keyword cAnteriorKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cAnteriorAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cAnteriorEStringParserRuleCall_5_0 = (RuleCall)cAnteriorAssignment_5.eContents().get(0);
		private final Keyword cNombreKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Assignment cNombreAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final RuleCall cNombreEStringParserRuleCall_7_0 = (RuleCall)cNombreAssignment_7.eContents().get(0);
		private final Keyword cSiguienteKeyword_8 = (Keyword)cGroup.eContents().get(8);
		private final Assignment cSiguienteAssignment_9 = (Assignment)cGroup.eContents().get(9);
		private final RuleCall cSiguienteEStringParserRuleCall_9_0 = (RuleCall)cSiguienteAssignment_9.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_10 = (Keyword)cGroup.eContents().get(10);
		
		//Flujo:
		//	{Flujo}
		//	'Flujo'
		//	name=EString
		//	'{'
		//	'anterior' anterior=EString
		//	'nombre' nombre=EString
		//	'siguiente' siguiente=EString
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//{Flujo} 'Flujo' name=EString '{' 'anterior' anterior=EString 'nombre' nombre=EString 'siguiente' siguiente=EString '}'
		public Group getGroup() { return cGroup; }
		
		//{Flujo}
		public Action getFlujoAction_0() { return cFlujoAction_0; }
		
		//'Flujo'
		public Keyword getFlujoKeyword_1() { return cFlujoKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//'anterior'
		public Keyword getAnteriorKeyword_4() { return cAnteriorKeyword_4; }
		
		//anterior=EString
		public Assignment getAnteriorAssignment_5() { return cAnteriorAssignment_5; }
		
		//EString
		public RuleCall getAnteriorEStringParserRuleCall_5_0() { return cAnteriorEStringParserRuleCall_5_0; }
		
		//'nombre'
		public Keyword getNombreKeyword_6() { return cNombreKeyword_6; }
		
		//nombre=EString
		public Assignment getNombreAssignment_7() { return cNombreAssignment_7; }
		
		//EString
		public RuleCall getNombreEStringParserRuleCall_7_0() { return cNombreEStringParserRuleCall_7_0; }
		
		//'siguiente'
		public Keyword getSiguienteKeyword_8() { return cSiguienteKeyword_8; }
		
		//siguiente=EString
		public Assignment getSiguienteAssignment_9() { return cSiguienteAssignment_9; }
		
		//EString
		public RuleCall getSiguienteEStringParserRuleCall_9_0() { return cSiguienteEStringParserRuleCall_9_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_10() { return cRightCurlyBracketKeyword_10; }
	}
	public class EStringElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "co.edu.javeriana.dfd.DFD.EString");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Group cGroup_0 = (Group)cAlternatives.eContents().get(0);
		private final Action cEStringAction_0_0 = (Action)cGroup_0.eContents().get(0);
		private final RuleCall cSTRINGTerminalRuleCall_0_1 = (RuleCall)cGroup_0.eContents().get(1);
		private final Group cGroup_1 = (Group)cAlternatives.eContents().get(1);
		private final Action cEStringAction_1_0 = (Action)cGroup_1.eContents().get(0);
		private final RuleCall cIDTerminalRuleCall_1_1 = (RuleCall)cGroup_1.eContents().get(1);
		
		//EString:
		//	{EString} STRING | {EString} ID;
		@Override public ParserRule getRule() { return rule; }
		
		//{EString} STRING | {EString} ID
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//{EString} STRING
		public Group getGroup_0() { return cGroup_0; }
		
		//{EString}
		public Action getEStringAction_0_0() { return cEStringAction_0_0; }
		
		//STRING
		public RuleCall getSTRINGTerminalRuleCall_0_1() { return cSTRINGTerminalRuleCall_0_1; }
		
		//{EString} ID
		public Group getGroup_1() { return cGroup_1; }
		
		//{EString}
		public Action getEStringAction_1_0() { return cEStringAction_1_0; }
		
		//ID
		public RuleCall getIDTerminalRuleCall_1_1() { return cIDTerminalRuleCall_1_1; }
	}
	public class ProcesoElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "co.edu.javeriana.dfd.DFD.Proceso");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cProcesoAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cProcesoKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		
		//Proceso:
		//	{Proceso}
		//	'Proceso'
		//	name=EString;
		@Override public ParserRule getRule() { return rule; }
		
		//{Proceso} 'Proceso' name=EString
		public Group getGroup() { return cGroup; }
		
		//{Proceso}
		public Action getProcesoAction_0() { return cProcesoAction_0; }
		
		//'Proceso'
		public Keyword getProcesoKeyword_1() { return cProcesoKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
	}
	public class EntidadExternaElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "co.edu.javeriana.dfd.DFD.EntidadExterna");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cEntidadExternaAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cEntidadExternaKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		
		//EntidadExterna:
		//	{EntidadExterna}
		//	'EntidadExterna'
		//	name=EString;
		@Override public ParserRule getRule() { return rule; }
		
		//{EntidadExterna} 'EntidadExterna' name=EString
		public Group getGroup() { return cGroup; }
		
		//{EntidadExterna}
		public Action getEntidadExternaAction_0() { return cEntidadExternaAction_0; }
		
		//'EntidadExterna'
		public Keyword getEntidadExternaKeyword_1() { return cEntidadExternaKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
	}
	public class AlmacenElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "co.edu.javeriana.dfd.DFD.Almacen");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cAlmacenAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cAlmacenKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		
		//Almacen:
		//	{Almacen}
		//	'Almacen'
		//	name=EString;
		@Override public ParserRule getRule() { return rule; }
		
		//{Almacen} 'Almacen' name=EString
		public Group getGroup() { return cGroup; }
		
		//{Almacen}
		public Action getAlmacenAction_0() { return cAlmacenAction_0; }
		
		//'Almacen'
		public Keyword getAlmacenKeyword_1() { return cAlmacenKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
	}
	
	
	private final DFDElements pDFD;
	private final ElementoElements pElemento;
	private final FlujoElements pFlujo;
	private final EStringElements pEString;
	private final ProcesoElements pProceso;
	private final EntidadExternaElements pEntidadExterna;
	private final AlmacenElements pAlmacen;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public DFDGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pDFD = new DFDElements();
		this.pElemento = new ElementoElements();
		this.pFlujo = new FlujoElements();
		this.pEString = new EStringElements();
		this.pProceso = new ProcesoElements();
		this.pEntidadExterna = new EntidadExternaElements();
		this.pAlmacen = new AlmacenElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("co.edu.javeriana.dfd.DFD".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//DFD:
	//	{DFD}
	//	'DFD'
	//	'{' ('flujo' '{' flujo+=Flujo ("," flujo+=Flujo)* '}')? ('elemento' '{' elemento+=Elemento ("," elemento+=Elemento)*
	//	'}')?
	//	'}';
	public DFDElements getDFDAccess() {
		return pDFD;
	}
	
	public ParserRule getDFDRule() {
		return getDFDAccess().getRule();
	}
	
	//Elemento:
	//	Proceso | EntidadExterna | Almacen;
	public ElementoElements getElementoAccess() {
		return pElemento;
	}
	
	public ParserRule getElementoRule() {
		return getElementoAccess().getRule();
	}
	
	//Flujo:
	//	{Flujo}
	//	'Flujo'
	//	name=EString
	//	'{'
	//	'anterior' anterior=EString
	//	'nombre' nombre=EString
	//	'siguiente' siguiente=EString
	//	'}';
	public FlujoElements getFlujoAccess() {
		return pFlujo;
	}
	
	public ParserRule getFlujoRule() {
		return getFlujoAccess().getRule();
	}
	
	//EString:
	//	{EString} STRING | {EString} ID;
	public EStringElements getEStringAccess() {
		return pEString;
	}
	
	public ParserRule getEStringRule() {
		return getEStringAccess().getRule();
	}
	
	//Proceso:
	//	{Proceso}
	//	'Proceso'
	//	name=EString;
	public ProcesoElements getProcesoAccess() {
		return pProceso;
	}
	
	public ParserRule getProcesoRule() {
		return getProcesoAccess().getRule();
	}
	
	//EntidadExterna:
	//	{EntidadExterna}
	//	'EntidadExterna'
	//	name=EString;
	public EntidadExternaElements getEntidadExternaAccess() {
		return pEntidadExterna;
	}
	
	public ParserRule getEntidadExternaRule() {
		return getEntidadExternaAccess().getRule();
	}
	
	//Almacen:
	//	{Almacen}
	//	'Almacen'
	//	name=EString;
	public AlmacenElements getAlmacenAccess() {
		return pAlmacen;
	}
	
	public ParserRule getAlmacenRule() {
		return getAlmacenAccess().getRule();
	}
	
	//terminal ID:
	//	'^'? ('a'..'z' | 'A'..'Z' | '_') ('a'..'z' | 'A'..'Z' | '_' | '0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt:
	//	'0'..'9'+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//	'"' ('\\' . | !('\\' | '"'))* '"' |
	//	"'" ('\\' . | !('\\' | "'"))* "'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT:
	//	'/*'->'*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT:
	//	'//' !('\n' | '\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS:
	//	' ' | '\t' | '\r' | '\n'+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
