/**
 * generated by Xtext 2.23.0
 */
package co.edu.javeriana.dfd.dFD;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see co.edu.javeriana.dfd.dFD.DFDFactory
 * @model kind="package"
 * @generated
 */
public interface DFDPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "dFD";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.edu.co/javeriana/dfd/DFD";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "dFD";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  DFDPackage eINSTANCE = co.edu.javeriana.dfd.dFD.impl.DFDPackageImpl.init();

  /**
   * The meta object id for the '{@link co.edu.javeriana.dfd.dFD.impl.DFDImpl <em>DFD</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see co.edu.javeriana.dfd.dFD.impl.DFDImpl
   * @see co.edu.javeriana.dfd.dFD.impl.DFDPackageImpl#getDFD()
   * @generated
   */
  int DFD = 0;

  /**
   * The feature id for the '<em><b>Flujo</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DFD__FLUJO = 0;

  /**
   * The feature id for the '<em><b>Elemento</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DFD__ELEMENTO = 1;

  /**
   * The number of structural features of the '<em>DFD</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DFD_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link co.edu.javeriana.dfd.dFD.impl.ElementoImpl <em>Elemento</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see co.edu.javeriana.dfd.dFD.impl.ElementoImpl
   * @see co.edu.javeriana.dfd.dFD.impl.DFDPackageImpl#getElemento()
   * @generated
   */
  int ELEMENTO = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ELEMENTO__NAME = 0;

  /**
   * The number of structural features of the '<em>Elemento</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ELEMENTO_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link co.edu.javeriana.dfd.dFD.impl.FlujoImpl <em>Flujo</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see co.edu.javeriana.dfd.dFD.impl.FlujoImpl
   * @see co.edu.javeriana.dfd.dFD.impl.DFDPackageImpl#getFlujo()
   * @generated
   */
  int FLUJO = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FLUJO__NAME = 0;

  /**
   * The feature id for the '<em><b>Anterior</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FLUJO__ANTERIOR = 1;

  /**
   * The feature id for the '<em><b>Nombre</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FLUJO__NOMBRE = 2;

  /**
   * The feature id for the '<em><b>Siguiente</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FLUJO__SIGUIENTE = 3;

  /**
   * The number of structural features of the '<em>Flujo</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FLUJO_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link co.edu.javeriana.dfd.dFD.impl.EStringImpl <em>EString</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see co.edu.javeriana.dfd.dFD.impl.EStringImpl
   * @see co.edu.javeriana.dfd.dFD.impl.DFDPackageImpl#getEString()
   * @generated
   */
  int ESTRING = 3;

  /**
   * The number of structural features of the '<em>EString</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ESTRING_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link co.edu.javeriana.dfd.dFD.impl.ProcesoImpl <em>Proceso</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see co.edu.javeriana.dfd.dFD.impl.ProcesoImpl
   * @see co.edu.javeriana.dfd.dFD.impl.DFDPackageImpl#getProceso()
   * @generated
   */
  int PROCESO = 4;

  /**
   * The feature id for the '<em><b>Name</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROCESO__NAME = ELEMENTO__NAME;

  /**
   * The number of structural features of the '<em>Proceso</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROCESO_FEATURE_COUNT = ELEMENTO_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link co.edu.javeriana.dfd.dFD.impl.EntidadExternaImpl <em>Entidad Externa</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see co.edu.javeriana.dfd.dFD.impl.EntidadExternaImpl
   * @see co.edu.javeriana.dfd.dFD.impl.DFDPackageImpl#getEntidadExterna()
   * @generated
   */
  int ENTIDAD_EXTERNA = 5;

  /**
   * The feature id for the '<em><b>Name</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENTIDAD_EXTERNA__NAME = ELEMENTO__NAME;

  /**
   * The number of structural features of the '<em>Entidad Externa</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENTIDAD_EXTERNA_FEATURE_COUNT = ELEMENTO_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link co.edu.javeriana.dfd.dFD.impl.AlmacenImpl <em>Almacen</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see co.edu.javeriana.dfd.dFD.impl.AlmacenImpl
   * @see co.edu.javeriana.dfd.dFD.impl.DFDPackageImpl#getAlmacen()
   * @generated
   */
  int ALMACEN = 6;

  /**
   * The feature id for the '<em><b>Name</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ALMACEN__NAME = ELEMENTO__NAME;

  /**
   * The number of structural features of the '<em>Almacen</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ALMACEN_FEATURE_COUNT = ELEMENTO_FEATURE_COUNT + 0;


  /**
   * Returns the meta object for class '{@link co.edu.javeriana.dfd.dFD.DFD <em>DFD</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>DFD</em>'.
   * @see co.edu.javeriana.dfd.dFD.DFD
   * @generated
   */
  EClass getDFD();

  /**
   * Returns the meta object for the containment reference list '{@link co.edu.javeriana.dfd.dFD.DFD#getFlujo <em>Flujo</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Flujo</em>'.
   * @see co.edu.javeriana.dfd.dFD.DFD#getFlujo()
   * @see #getDFD()
   * @generated
   */
  EReference getDFD_Flujo();

  /**
   * Returns the meta object for the containment reference list '{@link co.edu.javeriana.dfd.dFD.DFD#getElemento <em>Elemento</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Elemento</em>'.
   * @see co.edu.javeriana.dfd.dFD.DFD#getElemento()
   * @see #getDFD()
   * @generated
   */
  EReference getDFD_Elemento();

  /**
   * Returns the meta object for class '{@link co.edu.javeriana.dfd.dFD.Elemento <em>Elemento</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Elemento</em>'.
   * @see co.edu.javeriana.dfd.dFD.Elemento
   * @generated
   */
  EClass getElemento();

  /**
   * Returns the meta object for the containment reference '{@link co.edu.javeriana.dfd.dFD.Elemento#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Name</em>'.
   * @see co.edu.javeriana.dfd.dFD.Elemento#getName()
   * @see #getElemento()
   * @generated
   */
  EReference getElemento_Name();

  /**
   * Returns the meta object for class '{@link co.edu.javeriana.dfd.dFD.Flujo <em>Flujo</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Flujo</em>'.
   * @see co.edu.javeriana.dfd.dFD.Flujo
   * @generated
   */
  EClass getFlujo();

  /**
   * Returns the meta object for the containment reference '{@link co.edu.javeriana.dfd.dFD.Flujo#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Name</em>'.
   * @see co.edu.javeriana.dfd.dFD.Flujo#getName()
   * @see #getFlujo()
   * @generated
   */
  EReference getFlujo_Name();

  /**
   * Returns the meta object for the containment reference '{@link co.edu.javeriana.dfd.dFD.Flujo#getAnterior <em>Anterior</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Anterior</em>'.
   * @see co.edu.javeriana.dfd.dFD.Flujo#getAnterior()
   * @see #getFlujo()
   * @generated
   */
  EReference getFlujo_Anterior();

  /**
   * Returns the meta object for the containment reference '{@link co.edu.javeriana.dfd.dFD.Flujo#getNombre <em>Nombre</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Nombre</em>'.
   * @see co.edu.javeriana.dfd.dFD.Flujo#getNombre()
   * @see #getFlujo()
   * @generated
   */
  EReference getFlujo_Nombre();

  /**
   * Returns the meta object for the containment reference '{@link co.edu.javeriana.dfd.dFD.Flujo#getSiguiente <em>Siguiente</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Siguiente</em>'.
   * @see co.edu.javeriana.dfd.dFD.Flujo#getSiguiente()
   * @see #getFlujo()
   * @generated
   */
  EReference getFlujo_Siguiente();

  /**
   * Returns the meta object for class '{@link co.edu.javeriana.dfd.dFD.EString <em>EString</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>EString</em>'.
   * @see co.edu.javeriana.dfd.dFD.EString
   * @generated
   */
  EClass getEString();

  /**
   * Returns the meta object for class '{@link co.edu.javeriana.dfd.dFD.Proceso <em>Proceso</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Proceso</em>'.
   * @see co.edu.javeriana.dfd.dFD.Proceso
   * @generated
   */
  EClass getProceso();

  /**
   * Returns the meta object for class '{@link co.edu.javeriana.dfd.dFD.EntidadExterna <em>Entidad Externa</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Entidad Externa</em>'.
   * @see co.edu.javeriana.dfd.dFD.EntidadExterna
   * @generated
   */
  EClass getEntidadExterna();

  /**
   * Returns the meta object for class '{@link co.edu.javeriana.dfd.dFD.Almacen <em>Almacen</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Almacen</em>'.
   * @see co.edu.javeriana.dfd.dFD.Almacen
   * @generated
   */
  EClass getAlmacen();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  DFDFactory getDFDFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link co.edu.javeriana.dfd.dFD.impl.DFDImpl <em>DFD</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see co.edu.javeriana.dfd.dFD.impl.DFDImpl
     * @see co.edu.javeriana.dfd.dFD.impl.DFDPackageImpl#getDFD()
     * @generated
     */
    EClass DFD = eINSTANCE.getDFD();

    /**
     * The meta object literal for the '<em><b>Flujo</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DFD__FLUJO = eINSTANCE.getDFD_Flujo();

    /**
     * The meta object literal for the '<em><b>Elemento</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DFD__ELEMENTO = eINSTANCE.getDFD_Elemento();

    /**
     * The meta object literal for the '{@link co.edu.javeriana.dfd.dFD.impl.ElementoImpl <em>Elemento</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see co.edu.javeriana.dfd.dFD.impl.ElementoImpl
     * @see co.edu.javeriana.dfd.dFD.impl.DFDPackageImpl#getElemento()
     * @generated
     */
    EClass ELEMENTO = eINSTANCE.getElemento();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ELEMENTO__NAME = eINSTANCE.getElemento_Name();

    /**
     * The meta object literal for the '{@link co.edu.javeriana.dfd.dFD.impl.FlujoImpl <em>Flujo</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see co.edu.javeriana.dfd.dFD.impl.FlujoImpl
     * @see co.edu.javeriana.dfd.dFD.impl.DFDPackageImpl#getFlujo()
     * @generated
     */
    EClass FLUJO = eINSTANCE.getFlujo();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FLUJO__NAME = eINSTANCE.getFlujo_Name();

    /**
     * The meta object literal for the '<em><b>Anterior</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FLUJO__ANTERIOR = eINSTANCE.getFlujo_Anterior();

    /**
     * The meta object literal for the '<em><b>Nombre</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FLUJO__NOMBRE = eINSTANCE.getFlujo_Nombre();

    /**
     * The meta object literal for the '<em><b>Siguiente</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FLUJO__SIGUIENTE = eINSTANCE.getFlujo_Siguiente();

    /**
     * The meta object literal for the '{@link co.edu.javeriana.dfd.dFD.impl.EStringImpl <em>EString</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see co.edu.javeriana.dfd.dFD.impl.EStringImpl
     * @see co.edu.javeriana.dfd.dFD.impl.DFDPackageImpl#getEString()
     * @generated
     */
    EClass ESTRING = eINSTANCE.getEString();

    /**
     * The meta object literal for the '{@link co.edu.javeriana.dfd.dFD.impl.ProcesoImpl <em>Proceso</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see co.edu.javeriana.dfd.dFD.impl.ProcesoImpl
     * @see co.edu.javeriana.dfd.dFD.impl.DFDPackageImpl#getProceso()
     * @generated
     */
    EClass PROCESO = eINSTANCE.getProceso();

    /**
     * The meta object literal for the '{@link co.edu.javeriana.dfd.dFD.impl.EntidadExternaImpl <em>Entidad Externa</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see co.edu.javeriana.dfd.dFD.impl.EntidadExternaImpl
     * @see co.edu.javeriana.dfd.dFD.impl.DFDPackageImpl#getEntidadExterna()
     * @generated
     */
    EClass ENTIDAD_EXTERNA = eINSTANCE.getEntidadExterna();

    /**
     * The meta object literal for the '{@link co.edu.javeriana.dfd.dFD.impl.AlmacenImpl <em>Almacen</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see co.edu.javeriana.dfd.dFD.impl.AlmacenImpl
     * @see co.edu.javeriana.dfd.dFD.impl.DFDPackageImpl#getAlmacen()
     * @generated
     */
    EClass ALMACEN = eINSTANCE.getAlmacen();

  }

} //DFDPackage
