/**
 * generated by Xtext 2.23.0
 */
package co.edu.javeriana.dfd.dFD;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Elemento</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link co.edu.javeriana.dfd.dFD.Elemento#getName <em>Name</em>}</li>
 * </ul>
 *
 * @see co.edu.javeriana.dfd.dFD.DFDPackage#getElemento()
 * @model
 * @generated
 */
public interface Elemento extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' containment reference.
   * @see #setName(EString)
   * @see co.edu.javeriana.dfd.dFD.DFDPackage#getElemento_Name()
   * @model containment="true"
   * @generated
   */
  EString getName();

  /**
   * Sets the value of the '{@link co.edu.javeriana.dfd.dFD.Elemento#getName <em>Name</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' containment reference.
   * @see #getName()
   * @generated
   */
  void setName(EString value);

} // Elemento
