/**
 * generated by Xtext 2.23.0
 */
package co.edu.javeriana.dfd.dFD;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Entidad Externa</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see co.edu.javeriana.dfd.dFD.DFDPackage#getEntidadExterna()
 * @model
 * @generated
 */
public interface EntidadExterna extends Elemento
{
} // EntidadExterna
