/**
 * generated by Xtext 2.23.0
 */
package co.edu.javeriana.dfd.dFD;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>EString</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see co.edu.javeriana.dfd.dFD.DFDPackage#getEString()
 * @model
 * @generated
 */
public interface EString extends EObject
{
} // EString
