/**
 * generated by Xtext 2.23.0
 */
package co.edu.javeriana.dfd.dFD;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Flujo</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link co.edu.javeriana.dfd.dFD.Flujo#getName <em>Name</em>}</li>
 *   <li>{@link co.edu.javeriana.dfd.dFD.Flujo#getAnterior <em>Anterior</em>}</li>
 *   <li>{@link co.edu.javeriana.dfd.dFD.Flujo#getNombre <em>Nombre</em>}</li>
 *   <li>{@link co.edu.javeriana.dfd.dFD.Flujo#getSiguiente <em>Siguiente</em>}</li>
 * </ul>
 *
 * @see co.edu.javeriana.dfd.dFD.DFDPackage#getFlujo()
 * @model
 * @generated
 */
public interface Flujo extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' containment reference.
   * @see #setName(EString)
   * @see co.edu.javeriana.dfd.dFD.DFDPackage#getFlujo_Name()
   * @model containment="true"
   * @generated
   */
  EString getName();

  /**
   * Sets the value of the '{@link co.edu.javeriana.dfd.dFD.Flujo#getName <em>Name</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' containment reference.
   * @see #getName()
   * @generated
   */
  void setName(EString value);

  /**
   * Returns the value of the '<em><b>Anterior</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Anterior</em>' containment reference.
   * @see #setAnterior(EString)
   * @see co.edu.javeriana.dfd.dFD.DFDPackage#getFlujo_Anterior()
   * @model containment="true"
   * @generated
   */
  EString getAnterior();

  /**
   * Sets the value of the '{@link co.edu.javeriana.dfd.dFD.Flujo#getAnterior <em>Anterior</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Anterior</em>' containment reference.
   * @see #getAnterior()
   * @generated
   */
  void setAnterior(EString value);

  /**
   * Returns the value of the '<em><b>Nombre</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Nombre</em>' containment reference.
   * @see #setNombre(EString)
   * @see co.edu.javeriana.dfd.dFD.DFDPackage#getFlujo_Nombre()
   * @model containment="true"
   * @generated
   */
  EString getNombre();

  /**
   * Sets the value of the '{@link co.edu.javeriana.dfd.dFD.Flujo#getNombre <em>Nombre</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Nombre</em>' containment reference.
   * @see #getNombre()
   * @generated
   */
  void setNombre(EString value);

  /**
   * Returns the value of the '<em><b>Siguiente</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Siguiente</em>' containment reference.
   * @see #setSiguiente(EString)
   * @see co.edu.javeriana.dfd.dFD.DFDPackage#getFlujo_Siguiente()
   * @model containment="true"
   * @generated
   */
  EString getSiguiente();

  /**
   * Sets the value of the '{@link co.edu.javeriana.dfd.dFD.Flujo#getSiguiente <em>Siguiente</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Siguiente</em>' containment reference.
   * @see #getSiguiente()
   * @generated
   */
  void setSiguiente(EString value);

} // Flujo
