/**
 * generated by Xtext 2.23.0
 */
package co.edu.javeriana.dfd.dFD;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Proceso</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see co.edu.javeriana.dfd.dFD.DFDPackage#getProceso()
 * @model
 * @generated
 */
public interface Proceso extends Elemento
{
} // Proceso
