/*
 * generated by Xtext 2.23.0
 */
package co.edu.javeriana.dfd.ui;

import co.edu.javeriana.dfd.ui.internal.DfdActivator;
import com.google.inject.Injector;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class DFDExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(DfdActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		DfdActivator activator = DfdActivator.getInstance();
		return activator != null ? activator.getInjector(DfdActivator.CO_EDU_JAVERIANA_DFD_DFD) : null;
	}

}
