/*
 * generated by Xtext 2.23.0
 */
package co.edu.javeriana.dfd.ui.tests;

import co.edu.javeriana.dfd.ui.internal.DfdActivator;
import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;

public class DFDUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return DfdActivator.getInstance().getInjector("co.edu.javeriana.dfd.DFD");
	}

}
