/*
 * generated by Xtext 2.23.0
 */
package co.edu.javeriana.dfd.ide;

import co.edu.javeriana.dfd.DFDRuntimeModule;
import co.edu.javeriana.dfd.DFDStandaloneSetup;
import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class DFDIdeSetup extends DFDStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new DFDRuntimeModule(), new DFDIdeModule()));
	}
	
}
