/*
 * generated by Xtext 2.23.0
 */
package co.edu.javeriana.dfd.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class DFDAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("co/edu/javeriana/dfd/parser/antlr/internal/InternalDFD.tokens");
	}
}
