/*
 * generated by Xtext 2.23.0
 */
package co.edu.javeriana.dfd.parser.antlr;

import co.edu.javeriana.dfd.parser.antlr.internal.InternalDFDParser;
import co.edu.javeriana.dfd.services.DFDGrammarAccess;
import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class DFDParser extends AbstractAntlrParser {

	@Inject
	private DFDGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalDFDParser createParser(XtextTokenStream stream) {
		return new InternalDFDParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "DFD";
	}

	public DFDGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(DFDGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
